'use client'

import { useState } from 'react'
import { ArrowLeft, ArrowRight, Check, Sparkles, Volume2, VolumeX } from 'lucide-react'

const cards = [
  { title: 'Đứa trẻ bên trong', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/_Sometimes%20you%20will%20never%20know%20the%20value%20of%20a%20moment%20until%20it%20becomes%20a%20memory_%E2%9C%A8%EF%B8%8F%20~%20_pink%20_pinkaesthetic%20_lightpink%20_garden-pQHrFWpVs155w9E5Sa98tiEZP15v9X.jpeg', message: 'Có một phiên bản nhỏ bé của bạn vẫn đang chờ được lắng nghe. Những điều bạn từng nghĩ là “không đáng gì” có thể đã để lại dấu vết sâu hơn bạn tưởng. Hôm nay, thay vì trách mình vì quá nhạy cảm, hãy thử hỏi: “Ngày đó, mình thật sự cần điều gì?”', question: 'Nếu được ôm lấy phiên bản nhỏ tuổi của mình ngay lúc này, bạn muốn nói gì với em ấy?' },
  { title: 'Bạn có đang thật sự ổn?', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/e85b80dfd1c1ccf6c6bd5a111af86b8b-W6IOUtc4lwENpy8uEj9zs8cZArZjre.jpg', message: '“Mình ổn” đôi khi chỉ là câu nói bạn đã quá quen miệng. Bạn không cần phải mạnh mẽ mọi lúc. Có những cảm xúc không cần được sửa chữa, chỉ cần được nhìn thấy và gọi đúng tên.', question: 'Hôm nay, cảm xúc nào đang cần bạn thành thật gọi tên?' },
  { title: 'Nhìn lại chính mình', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/04a0900b103887cf370c2506e8207571-KjCk0Hnvrv98A3ZWRvnOh2b0vuvqAZ.jpg', message: 'Người khác có thể là tấm gương, nhưng không phải mọi điều họ nói về bạn đều là sự thật. Đừng vội định nghĩa bản thân bằng ánh mắt của người khác.', question: 'Nếu không cần sự công nhận của bất kỳ ai, bạn muốn trở thành người như thế nào?' },
  { title: 'Cảm xúc không phải kẻ thù', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/62f36df49d634a29c9e8e8d787afe457-rwouStalnuRnipRaSKTzM2AQSuRTKi.jpg', message: 'Bạn không xấu chỉ vì bạn tức giận. Bạn không yếu đuối chỉ vì bạn buồn. Cảm xúc không đến để chống lại bạn. Nó đến để nói cho bạn biết bên trong mình đang có chuyện gì.', question: 'Cảm xúc của bạn đang cố bảo vệ điều gì?' },
  { title: 'Buông một phiên bản cũ', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/39f0c0f7a4179c0d970f36244d072ba8-rcSbJJl4RoDZ2nW7AYHA8qcqJ27PQm.jpg', message: 'Có những phiên bản của bạn từng rất cần thiết để bạn tồn tại. Nhưng không phải phiên bản nào cũng cần đi cùng bạn mãi mãi. Bạn có quyền thay đổi cách yêu, cách phản ứng, cách bảo vệ mình.', question: 'Điều gì bạn đã sẵn sàng nhẹ nhàng đặt xuống?' },
  { title: 'Đừng phản ứng quá nhanh', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/4019c97ebb852e803c95300e4226e78a-CEkBX3Uwoo1YLReP2DSAFn5V7UDllr.jpg', message: 'Có những lúc bạn không thật sự tức giận với người trước mặt. Bạn chỉ đang phản ứng với một vết thương cũ vừa bị chạm vào. Hãy dừng lại vài giây và hỏi: “Điều gì trong mình vừa bị chạm tới?”', question: 'Bạn cần thêm bao nhiêu khoảng lặng trước khi trả lời?' },
  { title: 'Bạn không cần phải hoàn hảo', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/5ad50b40d483950517ecd93a08c562c9-Em0hTGmQbj9HMx121TLWzJJWSxqiCv.jpg', message: 'Bạn không cần trở thành một phiên bản hoàn hảo hơn để xứng đáng được yêu thương. Phát triển bản thân là hiểu mình hơn, chấp nhận mình hơn, rồi từng chút một thay đổi những điều không còn phù hợp.', question: 'Hôm nay bạn có thể dịu dàng với mình ở điểm nào?' },
  { title: 'Điều bạn đang né tránh', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/0830728cb7eccdb519a99d4f53c9f590-Vv0O86D40TwnTlK5AGDYugPDkVxkZw.jpg', message: 'Có một điều bạn biết mình cần đối diện, nhưng vẫn đang cố lảng tránh. Bạn không cần giải quyết tất cả ngay hôm nay. Nhưng hãy đủ can đảm để thừa nhận: “Ừ, mình đang né tránh điều này.”', question: 'Một điều nhỏ bạn có thể thành thật với chính mình hôm nay là gì?' },
  { title: 'Học cách hiểu mình', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/436da258c38945e42b0b77553c29547c-cRR9ZoqYOkLODHPOlxILyHdPGQ3jEp.jpg', message: 'Bạn dành rất nhiều thời gian để đoán xem người khác nghĩ gì về mình. Nhưng đã bao lâu rồi bạn chưa thật sự hỏi chính mình: “Mình đang muốn gì? Mình đang cảm thấy gì?”', question: 'Điều gì khiến bạn hạnh phúc theo cách rất riêng?' },
  { title: 'Bạn đang thay đổi rồi', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/83e4b49dc6880ef2de718c6d1f91ce8b-dzwyz4yLg8KOrZMC8FnsSkXqwmuv5w.jpg', message: 'Có thể bạn chưa nhận ra, nhưng cách bạn nhìn mọi chuyện hôm nay đã khác ngày trước. Biết dừng lại, biết nói “không”, biết bảo vệ cảm xúc — đó đều là những dấu hiệu của trưởng thành.', question: 'Bạn đã đi được bao xa mà chưa kịp ghi nhận?' },
]

type Step = 'pick' | 'message' | 'quiz' | 'result' | 'invite' | 'coaching' | 'form' | 'done'

export default function Page() {
  const [step, setStep] = useState<Step>('pick')
  const [selected, setSelected] = useState<number | null>(null)
  const [form, setForm] = useState({ name: '', birthYear: '', gender: '', phone: '', contactTime: '', wish: '' })
  const [reflection, setReflection] = useState('')
  const [answers, setAnswers] = useState<Record<number, string>>({})
  const card = selected === null ? null : cards[selected]
  async function submitQuiz() { await fetch('/api/submissions', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...form, selectedCard: card?.title || '', reflection, quizAnswers: answers }) }); setStep('done') }

  if (step === 'done') return <main className="tarot-page"><Header /><section className="center-panel"><span className="tiny-symbol"><Sparkles /></span><p className="kicker">CẢM ƠN BẠN</p><h1>Cảm ơn bạn đã sẵn sàng dành thời gian cho chính mình. 🌱</h1><p>Có thể bạn đến đây chỉ vì tò mò muốn biết “vũ trụ muốn nói gì với mình”. Nhưng biết đâu, điều bạn thật sự tìm thấy lại là một phiên bản của chính mình mà lâu nay bạn chưa có cơ hội lắng nghe.</p><strong>Chúng tôi sẽ liên hệ với bạn trong 1~2 ngày nữa nếu bạn được chọn. Hẹn gặp bạn trong buổi coaching nhé. 🤍</strong></section></main>

  return <main className="tarot-page"><Header /><AudioPlayer /><div className="tarot-wrap">
    {step === 'pick' && <><section className="hero-copy"><p className="kicker">A LITTLE MESSAGE FROM THE UNIVERSE</p><h1>Hôm nay vũ trụ muốn<br /><em>nhắn nhủ bạn điều gì?</em></h1><p>Hít một hơi thật sâu. Nghĩ về điều đang khiến bạn bận lòng nhất lúc này.</p><p>Chọn một lá bài. Có thể thông điệp này chính là điều bạn cần nghe hôm nay.</p></section><CardGrid onPick={(index) => { void fetch('/api/visits', { method: 'POST' }); setSelected(index); setStep('message') }} /></>}
    {step === 'message' && card && <Message card={card} reflection={reflection} setReflection={setReflection} onNext={() => setStep('quiz')} onBack={() => setStep('pick')} />}
    {step === 'quiz' && card && <SelfQuiz card={card} answers={answers} setAnswers={setAnswers} onNext={() => setStep('result')} onBack={() => setStep('message')} />}
    {step === 'result' && card && <QuizResult card={card} onNext={() => setStep('invite')} onBack={() => setStep('quiz')} />}
    {step === 'invite' && <Invite onNext={() => setStep('coaching')} onLater={() => setStep('done')} onBack={() => setStep('result')} />} 
    {step === 'coaching' && <CoachingMessage onReady={() => setStep('form')} onNotReady={() => setStep('done')} onBack={() => setStep('invite')} />}
    {step === 'form' && <CoachingForm form={form} setForm={setForm} onSubmit={submitQuiz} onBack={() => setStep('invite')} />}
  </div><footer>một khoảng lặng nhỏ để lắng nghe chính mình · 2026</footer></main>
}

function AudioPlayer() { const [isPlaying, setIsPlaying] = useState(false); const videoUrl = 'https://www.youtube-nocookie.com/embed/vELBkxa-8EQ?autoplay=1&controls=0&loop=1&playlist=vELBkxa-8EQ&modestbranding=1&rel=0'; return <div className="audio-player"><button type="button" className="audio-toggle" onClick={() => setIsPlaying((value) => !value)} aria-label={isPlaying ? 'Tắt nhạc nền' : 'Bật nhạc nền'}>{isPlaying ? <Volume2 size={16} /> : <VolumeX size={16} />}<span>{isPlaying ? 'Đang phát nhạc' : 'Bật nhạc nền'}</span></button>{isPlaying && <iframe className="audio-frame" src={videoUrl} title="Nhạc nền thư giãn" allow="autoplay; encrypted-media" />}</div> }

function Header() { return <header className="tarot-header"><div className="brand"><span className="brand-icon"><Sparkles size={16} /></span> INNER / COMPASS</div><span className="header-note">SELF-AWARENESS JOURNAL</span></header> }
function CardGrid({ onPick }: { onPick: (index: number) => void }) { return <section className="card-grid" aria-label="Chọn một lá bài">{cards.map((card, index) => <button className="tarot-card" aria-label={`Chọn lá bài số ${index + 1}`} key={card.title} onClick={() => onPick(index)}><img src={card.image} alt="" /></button>)}</section> }
function Message({ card, reflection, setReflection, onNext, onBack }: { card: typeof cards[number]; reflection: string; setReflection: (value: string) => void; onNext: () => void; onBack: () => void }) { return <section className="message-layout"><button className="back-link" onClick={onBack}><ArrowLeft size={15} /> Chọn lại lá bài</button><div className="message-image"><img src={card.image} alt={card.title} /></div><div className="message-copy"><p className="kicker">THÔNG ĐIỆP DÀNH CHO BẠN HÔM NAY</p><h1>{card.title}</h1><p className="message-text">{card.message}</p><div className="reflection-box"><span>✦ Một câu hỏi dành cho bạn</span><p>“{card.question}”</p><textarea aria-label="Câu trả lời của bạn" value={reflection} onChange={(event) => setReflection(event.target.value)} placeholder="Viết điều đầu tiên xuất hiện trong tâm trí bạn..." /></div><button className="primary-button" onClick={onNext}>Cùng đi tìm hiểu chính mình nhé <ArrowRight size={16} /></button></div></section> }
const quizSets: Record<string, string[][]> = {
  'Đứa trẻ bên trong': [['Khi nhớ về những chuyện từng khiến bạn tổn thương, bạn thường…', 'Nghĩ rằng “chuyện qua rồi, không có gì đâu”', 'Vẫn cảm thấy buồn nhưng không biết vì sao', 'Tránh nghĩ về nó vì không muốn cảm nhận lại', 'Bắt đầu muốn hiểu vì sao nó vẫn ảnh hưởng đến mình'], ['Khi ai đó vô tình nói một câu khiến bạn tổn thương, bạn thường…', 'Im lặng và giả vờ như không có chuyện gì', 'Phản ứng ngay vì cảm thấy mình bị xúc phạm', 'Suy nghĩ rất nhiều về câu nói đó', 'Cố gắng hiểu cảm xúc của mình trước khi phản ứng'], ['Bạn có thường tự trách mình vì những cảm xúc của bản thân không?', 'Rất thường xuyên', 'Thỉnh thoảng', 'Chỉ khi cảm xúc của mình ảnh hưởng đến người khác', 'Mình đang học cách chấp nhận cảm xúc của mình'], ['Nếu được thay đổi một điều ở bản thân hiện tại, bạn muốn thay đổi điều gì nhất?', 'Cách mình đối xử với chính mình', 'Cách mình phản ứng khi tổn thương', 'Cách mình giao tiếp và kết nối với người khác', 'Mình chưa biết, nhưng mình muốn hiểu bản thân hơn']],
  'Bạn có đang thật sự ổn?': [['Khi ai đó hỏi “Dạo này bạn ổn không?”, bạn thường…', '“Ổn mà” dù bên trong không ổn lắm', 'Không biết phải trả lời thế nào', 'Chỉ chia sẻ khi mọi thứ đã quá sức', 'Có thể thành thật về cảm xúc của mình'], ['Khi buồn, bạn thường làm gì?', 'Giấu đi và tiếp tục mọi việc', 'Tìm thứ gì đó để bản thân bận rộn', 'Tìm một người để tâm sự', 'Cho phép mình buồn và tìm hiểu nguyên nhân'], ['Bạn có dễ nhận ra mình đang căng thẳng không?', 'Thường chỉ nhận ra khi đã quá mệt', 'Nhận ra nhưng thường bỏ qua', 'Khá dễ nhận ra', 'Mình đang học cách lắng nghe những dấu hiệu của cơ thể và cảm xúc'], ['Khi cảm xúc tiêu cực xuất hiện, bạn thường nghĩ…', '“Mình không nên cảm thấy như vậy”', '“Ước gì cảm xúc này biến mất”', '“Chắc mình đang có chuyện gì đó”', '“Mình muốn hiểu cảm xúc này đang muốn nói gì với mình”']],
  'Nhìn lại chính mình': [['Bạn thường quan tâm đến đánh giá của người khác ở mức nào?', 'Rất nhiều, đôi khi ảnh hưởng đến quyết định của mình', 'Khá nhiều nhưng mình cố không để tâm', 'Có quan tâm nhưng vẫn giữ ý kiến riêng', 'Mình ưu tiên điều mình thật sự muốn'], ['Khi bị người khác góp ý, phản ứng đầu tiên của bạn là…', 'Cảm thấy mình không đủ tốt', 'Khó chịu hoặc muốn phản bác', 'Suy nghĩ xem họ nói có đúng không', 'Lắng nghe trước rồi tự nhìn lại'], ['Bạn có thường so sánh bản thân với người khác không?', 'Rất thường xuyên', 'Thỉnh thoảng', 'Chỉ khi mình cảm thấy chưa đủ tốt', 'Mình đang học cách tập trung vào hành trình của mình'], ['Điều gì khiến bạn cảm thấy mình có giá trị nhất?', 'Được người khác công nhận', 'Đạt được thành tích', 'Được yêu thương và trân trọng', 'Biết mình là ai và sống đúng với điều đó']],
  'Cảm xúc không phải kẻ thù': [['Khi tức giận, bạn thường…', 'Bùng nổ ngay lập tức', 'Im lặng và giữ trong lòng', 'Cố tìm nguyên nhân khiến mình tức giận', 'Cho mình thời gian bình tĩnh trước khi phản ứng'], ['Khi bị tổn thương, bạn thường…', 'Làm như không có chuyện gì', 'Xa cách người khiến mình tổn thương', 'Muốn được người đó hiểu cảm xúc của mình', 'Tìm cách nói ra cảm xúc một cách rõ ràng'], ['Bạn có phân biệt được “mình đang cảm thấy gì” và “mình đang nghĩ gì” không?', 'Khá khó', 'Đôi khi phân biệt được', 'Thường nhận ra', 'Mình khá hiểu cảm xúc của mình'], ['Khi cảm xúc quá mạnh, điều gì giúp bạn bình tĩnh nhất?', 'Tránh xa mọi người', 'Làm việc khác để quên đi', 'Nói chuyện với người mình tin tưởng', 'Dừng lại, hít thở và quan sát cảm xúc của mình']],
  'Buông một phiên bản cũ': [['Khi sợ bị tổn thương, bạn thường…', 'Không cho ai đến quá gần', 'Cố tỏ ra mình không cần ai', 'Dễ nghi ngờ người khác', 'Vẫn mở lòng nhưng biết đặt giới hạn'], ['Bạn có thường giữ những mối quan hệ đã không còn phù hợp không?', 'Rất khó buông', 'Vì sợ làm người khác tổn thương', 'Chỉ khi mình vẫn còn hy vọng', 'Mình biết khi nào cần bước đi'], ['Khi nhận ra mình đã thay đổi, bạn thường…', 'Sợ rằng mình đang trở thành một người khác', 'Cố quay lại như trước', 'Mất thời gian để thích nghi', 'Chấp nhận rằng thay đổi là một phần của trưởng thành'], ['Có một điều bạn biết mình cần buông nhưng chưa làm được.', 'Có', 'Có, nhưng mình chưa biết bắt đầu từ đâu', 'Mình ������ang cố gắng', 'Mình đã bắt đầu buông rồi']],
  'Đừng phản ứng quá nhanh': [['Khi ai đó làm điều khiến b���n khó chịu, bạn thường…', 'Phản ứng ngay', 'Im lặng nhưng tức rất lâu', 'Rời khỏi tình huống để bình tĩnh', 'Tìm hiểu cảm xúc trước khi quyết định phản ứng'], ['Sau một cuộc tranh cãi, bạn thường…', 'Nghĩ rằng người kia sai', 'Tự trách mình', 'Nghĩ đi nghĩ lại xem chuyện gì đã xảy ra', 'Nhìn lại cả cách mình và đối phương đã phản ứng'], ['Bạn có từng nói điều gì đó trong lúc tức giận rồi hối hận không?', 'Rất thường xuyên', 'Thỉnh thoảng', 'Hiếm khi', 'Mình đang học cách dừng lại trước khi nói'], ['Khi bị chạm vào “điểm đau”, bạn thường nhận ra điều đó…', 'Sau khi đã phản ứng', 'Một lúc sau', 'Khá nhanh', 'Ngay lúc cảm xúc bắt đầu xuất hiện']],
  'Bạn không cần phải hoàn hảo': [['Khi mắc lỗi, bạn thường nói với chính mình…', 'Sao mình lại ngu như vậy?', 'Giá như mình làm tốt hơn', 'Lần sau mình sẽ chú ý hơn', 'Mình vẫn có thể học từ điều này'], ['Bạn có thường cảm thấy mình “chưa đủ tốt” không?', 'Rất thường xuyên', 'Khá thường xuyên', 'Thỉnh thoảng', 'Mình đang học cách công nhận bản thân'], ['Khi người khác thành công hơn mình, bạn thường…', 'Cảm thấy mình thua kém', 'Tự hỏi tại sao mình chưa làm được', 'Có chút chạnh lòng nhưng vẫn tiếp tục', 'Lấy đó làm động lực cho hành trình của mình'], ['Bạn đối xử với bản thân thế nào khi thất bại?', 'Khắt khe', 'Khá thất vọng', 'Cho mình thời gian rồi tiếp tục', 'Dịu dàng nhưng vẫn có trách nhiệm']],
  'Điều bạn đang né tránh': [['Có một vấn đề bạn biết mình cần giải quyết nhưng vẫn trì hoãn?', 'Có, rất nhiều', 'Có một vài điều', 'Có nhưng mình đang chuẩn bị', 'Mình đang chủ động đối diện với nó'], ['Khi gặp một vấn đề khó, bạn thường…', 'Né tránh', 'Chờ mọi thứ tự tốt lên', 'Tìm lời khuyên từ người khác', 'Chia nhỏ vấn đề và giải quyết từng bước'], ['Điều gì khiến bạn khó đối diện với vấn đề nhất?', 'Sợ kết quả', 'Sợ làm người khác thất vọng', 'Không biết mình thật sự muốn gì', 'Mình sợ nhưng vẫn muốn thử đối diện'], ['Nếu biết chắc không ai phán xét mình, bạn sẽ thay đổi điều gì đầu tiên?', 'Một mối quan hệ', 'Công việc / hướng đi', 'Cách mình sống và chăm sóc bản thân', 'Cách mình nhìn nhận chính mình']],
  'Học cách hiểu mình': [['Bạn có biết điều gì thật sự khiến mình hạnh phúc không?', 'Không chắc', 'Có vài điều', 'Khá rõ', 'Mình biết điều gì phù hợp với mình'], ['Khi phải đưa ra quyết định quan trọng, bạn thường dựa vào…', 'Người khác nghĩ gì', 'Điều an toàn nhất', 'Lý trí và hoàn cảnh', 'Cả lý trí, cảm xúc và điều mình thật sự muốn'], ['Bạn có thường dành thời gian một mình để nhìn lại bản thân không?', 'Gần như không', 'Thỉnh thoảng', 'Khá thường xuyên', 'Đây là một phần trong cuộc sống của mình'], ['Điều bạn muốn hiểu rõ nhất về bản thân lúc này là gì?', 'Mình thật sự muốn gì', 'Vì sao mình thường phản ứng như vậy', 'Mình cần gì để cảm thấy hạnh phúc', 'Mình muốn trở thành ai trong tương lai']],
  'Bạn đang thay đổi rồi': [['Bạn có nhận ra mình đã thay đổi không?', 'Mình chưa từng nghĩ về điều đó', 'Có, nhưng mình không biết cụ thể là gì', 'Có một vài điều mình nhận thấy', 'Mình nhìn thấy khá rõ sự thay đổi của mình'], ['Khi gặp lại một tình huống từng khiến bạn tổn thương, bạn có phản ứng khác trước không?', 'Vẫn giống như trước', 'Đôi khi khác', 'Mình đã biết dừng lại', 'Mình hiểu bản thân hơn nên phản ứng khác đi'], ['Điều gì khiến bạn cảm thấy mình trưởng thành hơn?', 'Không còn cố làm hài lòng tất cả mọi người', 'Biết nói “không”', 'Biết chịu trách nhiệm với cảm xúc của mình', 'Biết mình là ai và mình muốn gì'], ['Nếu được nhắn một câu cho “bạn của ngày hôm qua”, bạn sẽ nói gì?', 'Đừng sợ.', 'Bạn đã làm tốt hơn bạn nghĩ.', 'Hãy yêu thương bản thân nhiều hơn.', 'Cảm ơn vì đã cố gắng đưa chúng ta đến ngày hôm nay.']],
}

function SelfQuiz({ card, answers, setAnswers, onNext, onBack }: { card: typeof cards[number]; answers: Record<number, string>; setAnswers: (value: Record<number, string>) => void; onNext: () => void; onBack: () => void }) { const rows = quizSets[card.title] ?? []; const questions = rows.map(([question]) => question); return <section className="quiz-panel"><button className="back-link" onClick={onBack}><ArrowLeft size={15} /> Quay lại</button><p className="kicker quiz-kicker">🌱 MỘT CHÚT DÀNH CHO CHÍNH BẠN</p><h1>Cùng lắng nghe chính mình</h1><p className="quiz-intro">Không có câu trả lời đúng hay sai. Hãy chọn điều gần với bạn nhất.</p><div className="quiz-list">{rows.map(([question, ...options], index) => <div className="question-card" key={question}><p className="question-title">{index + 1}. {question}</p><div className="option-grid">{options.map((option) => <label className={`quiz-option ${answers[index] === option ? 'is-selected' : ''}`} key={option}><input type="radio" name={`question-${index}`} value={option} checked={answers[index] === option} onChange={() => setAnswers({ ...answers, [index]: option })} />{option}</label>)}</div></div>)}</div><button className="primary-button quiz-submit" disabled={Object.keys(answers).length < questions.length} onClick={onNext}>Tiếp tục <ArrowRight size={16} /></button></section> }

const quizResults: Record<string, { label: string; title: string; summary: string; strengths: string[]; growth: string[]; message: string }> = {
  'Đứa trẻ bên trong': { label: 'CARD 01 — ĐỨA TRẺ BÊN TRONG', title: 'Bạn là người có chiều sâu cảm xúc', summary: 'Bạn thường cảm nhận mọi thứ khá sâu, nhưng không phải lúc nào cũng biết cách gọi tên cảm xúc của mình. Những trải nghiệm trong quá khứ có thể vẫn ảnh hưởng đến cách bạn nhìn nhận bản thân và các mối quan hệ hiện tại.', strengths: ['Giàu sự đồng cảm', 'Nhạy bén với cảm xúc của người khác', 'Có khả năng nhìn sâu vào bản thân'], growth: ['Học cách gọi tên cảm xúc', 'Không tự trách mình vì những tổn thương trong quá khứ', 'Học cách chăm sóc “đứa trẻ bên trong” thay vì né tránh nó'], message: 'Bạn không cần thay đổi quá khứ. Bạn chỉ cần thay đổi cách mình đối xử với phiên bản đã từng tổn thương ấy.' },
  'Bạn có đang thật sự ổn?': { label: 'CARD 02 — BẠN CÓ THẬT SỰ ỔN?', title: 'Bạn là người thường cố gắng mạnh mẽ', summary: 'Bạn có xu hướng tự mình chịu đựng và không muốn trở thành gánh nặng cho người khác. Bạn có thể nói “mình ổn” ngay cả khi bên trong đang có rất nhiều điều chưa được giải quyết.', strengths: ['Có khả năng chịu đựng', 'Độc lập', 'Có trách nhiệm với cuộc sống của mình'], growth: ['Cho phép bản thân được yếu đuối', 'Thành thật hơn với cảm xúc', 'Biết tìm kiếm sự hỗ trợ khi cần'], message: 'Mạnh mẽ không có nghĩa là lúc nào cũng phải tự mình chịu đựng.' },
  'Nhìn lại chính mình': { label: 'CARD 03 — NHÌN LẠI CHÍNH MÌNH', title: 'Bạn là người dễ bị ảnh hưởng bởi ánh nhìn bên ngoài', summary: 'Bạn có thể dành khá nhiều năng lượng để suy nghĩ người khác nghĩ gì về mình. Đôi khi bạn biết mình muốn gì, nhưng lại chần chừ vì sợ lựa chọn của mình không được công nhận.', strengths: ['Biết quan sát bản thân', 'Quan tâm đến cảm nhận của người khác', 'Có khả năng thích nghi tốt'], growth: ['Xây dựng giá trị bản thân từ bên trong', 'Bớt so sánh', 'Học cách đưa ra lựa chọn dựa trên điều mình thật sự muốn'], message: 'Bạn không cần trở thành phiên bản mà mọi người thích. Bạn cần trở thành phiên bản mà chính bạn có thể tự hào.' },
  'Cảm xúc không phải kẻ thù': { label: 'CARD 04 — CẢM XÚC KHÔNG PHẢI KẺ THÙ', title: 'Bạn là người đang học cách làm bạn với cảm xúc', summary: 'Bạn có nhiều cảm xúc nhưng đôi khi chưa biết cách xử lý chúng. Có lúc bạn cố kiểm soát, né tránh hoặc phản ứng quá nhanh thay vì lắng nghe điều cảm xúc đang muốn nói.', strengths: ['Cảm nhận mọi thứ rõ ràng', 'Có khả năng đồng cảm', 'Khi hiểu được cảm xúc, bạn có khả năng thay đổi rất nhanh'], growth: ['Không phán xét cảm xúc của mình', 'Học cách dừng lại trước khi phản ứng', 'Phân biệt “mình đang cảm thấy gì” với “mình nên làm gì”'], message: 'Cảm xúc chỉ là tín hiệu. Bạn mới là người quyết định mình sẽ làm gì với tín hiệu đó.' },
  'Buông một phiên bản cũ': { label: 'CARD 05 — BUÔNG MỘT PHIÊN BẢN CŨ', title: 'Bạn là người trung thành với những điều từng quan trọng', summary: 'Bạn có thể giữ lại một số thói quen, cách phản ứng hoặc mối quan hệ vì chúng từng giúp bạn cảm thấy an toàn. Nhưng đôi khi điều từng bảo vệ bạn trong quá khứ lại đang giới hạn bạn ở hiện tại.', strengths: ['Sống tình cảm', 'Có sự gắn bó sâu sắc', 'Không dễ dàng từ bỏ người hoặc điều mình trân trọng'], growth: ['Nhận ra điều gì đã không còn phù hợp', 'Học cách đặt ranh giới', 'Cho phép bản thân bước sang một giai đoạn mới'], message: 'Buông bỏ không có nghĩa là phủ nhận những gì đã từng quan trọng.' },
  'Đừng phản ứng quá nhanh': { label: 'CARD 06 — ĐỪNG PHẢN ỨNG QUÁ NHANH', title: 'Bạn là người có cảm xúc mạnh', summary: 'Khi bị chạm vào một điểm nhạy cảm, phản ứng của bạn có thể đến trước khi bạn kịp hiểu chuyện gì đang xảy ra bên trong. Đôi khi vấn đề không nằm hoàn toàn ở hiện tại, mà còn liên quan đến những trải nghiệm trước đó.', strengths: ['Sống thật với cảm xúc', 'Có chính kiến', 'Không dễ dàng chịu đựng sự bất công'], growth: ['Tạo khoảng dừng trước khi phản ứng', 'Tìm hiểu “trigger” của bản thân', 'Học cách nói ra cảm xúc thay vì chỉ phản ứng'], message: 'Khoảng dừng vài giây đôi khi có thể thay đổi hoàn toàn cách một câu chuyện kết thúc.' },
  'Bạn không cần phải hoàn hảo': { label: 'CARD 07 — BẠN KHÔNG CẦN HOÀN HẢO', title: 'Bạn là người có tiêu chuẩn cao với chính mình', summary: 'Bạn luôn muốn mình tốt hơn, giỏi hơn và làm mọi thứ thật tốt. Nhưng đôi khi chính sự cầu toàn ấy khiến bạn quên mất rằng mình cũng cần được công nhận ngay cả khi chưa hoàn hảo.', strengths: ['Có tinh thần phát triển', 'Có trách nhiệm', 'Luôn muốn tiến bộ'], growth: ['Bớt tự phê bình', 'Chấp nhận sai lầm như một phần của quá trình', 'Học cách ghi nhận những tiến bộ nhỏ'], message: 'Phát triển bản thân không phải là trở thành người hoàn hảo. Là trở thành người hiểu mình hơn mỗi ngày.' },
  'Điều bạn đang né tránh': { label: 'CARD 08 — ĐIỀU BẠN ĐANG NÉ TRÁNH', title: 'Bạn là người thường cần thời gian để đối diện', summary: 'Bạn có thể biết mình cần thay đổi nhưng vẫn trì hoãn vì sợ kết quả, sợ mất đi điều quen thuộc hoặc đơn giản là chưa biết bắt đầu từ đâu.', strengths: ['Thận trọng', 'Có khả năng suy nghĩ sâu', 'Không dễ đưa ra quyết định bốc đồng'], growth: ['Đừng chờ đến khi “sẵn sàng 100%”', 'Chia vấn đề lớn thành những bước nhỏ', 'Thành thật với điều mình đang né tránh'], message: 'Bạn không cần biết toàn bộ con đường. Đôi khi chỉ cần đủ can đảm để bước bước đầu tiên.' },
  'Học cách hiểu mình': { label: 'CARD 09 — HỌC CÁCH HIỂU MÌNH', title: 'Bạn là người đang trên hành trình tìm chính mình', summary: 'Bạn có nhiều câu hỏi về cuộc sống, công việc, các mối quan hệ và chính bản thân. Có thể bạn chưa có tất cả câu trả lời — và điều đó hoàn toàn bình thường.', strengths: ['Có khả năng tự phản tỉnh', 'Ham học hỏi', 'Muốn sống có ý nghĩa'], growth: ['Dành thời gian lắng nghe chính mình', 'Phân biệt mong muốn của mình với kỳ vọng của người khác', 'Cho phép bản thân thử và sai'], message: 'Bạn không cần tìm thấy chính mình ngay lập tức. Bạn đang tạo ra chính mình qua từng lựa chọn mỗi ngày.' },
  'Bạn đang thay đổi rồi': { label: 'CARD 10 — BẠN ĐANG THAY ĐỔI', title: 'Bạn là người đang trưởng thành từ bên trong', summary: 'Bạn có thể chưa nhận thấy mình đã thay đổi nhiều như thế nào. Nhưng cách bạn nhìn nhận cảm xúc, các mối quan hệ và chính mình có lẽ đã khác trước.', strengths: ['Có khả năng tự nhìn lại', 'Biết học từ trải nghiệm', 'Có tinh thần phát triển'], growth: ['Đừng quá tập trung vào những gì mình chưa đạt được', 'Ghi nhận hành trình của bản thân', 'Tiếp tục thay đổi nhưng đừng đánh mất chính mình'], message: 'Đôi khi trưởng thành không phải là trở thành một người hoàn toàn khác. Mà là trở thành phiên bản hiểu mình hơn.' },
}

function QuizResult({ card, onNext, onBack }: { card: typeof cards[number]; onNext: () => void; onBack: () => void }) { const result = quizResults[card.title]; if (!result) return <Invite onNext={onNext} onLater={onNext} onBack={onBack} />; return <section className="result-panel"><span className="result-sticker sticker-sparkle" aria-hidden="true">✦</span><span className="result-sticker sticker-flower" aria-hidden="true">✿</span><span className="result-sticker sticker-heart" aria-hidden="true">♡</span><button className="back-link" onClick={onBack}><ArrowLeft size={15} /> Làm lại trắc nghiệm</button><p className="kicker">{result.label}</p><h1>{result.title}</h1><p className="result-summary">{result.summary}</p><div className="result-columns"><div><h2>Điểm mạnh</h2><ul>{result.strengths.map((item) => <li key={item}>{item}</li>)}</ul></div><div><h2>Điều cần phát triển</h2><ul>{result.growth.map((item) => <li key={item}>{item}</li>)}</ul></div></div><blockquote><span>Thông điệp dành cho bạn</span><p>{result.message}</p></blockquote><button className="primary-button" onClick={onNext}>Tiếp tục <ArrowRight size={16} /></button></section> }

function Invite({ onNext, onLater, onBack }: { onNext: () => void; onLater: () => void; onBack: () => void }) { return <section className="center-panel flow-panel"><button className="back-link" onClick={onBack}><ArrowLeft size={15} /> Quay lại</button><span className="tiny-symbol">🌱</span><p className="kicker">MỘT CHÚT DÀNH CHO CHÍNH BẠN</p><h1>Bạn có muốn hiểu thêm về bản thân mình không?</h1><p>Có những điều bên trong chúng ta chỉ nhận ra khi thật sự dành thời gian lắng nghe chính mình.</p><div className="choice-actions"><button className="primary-button" onClick={onNext}>Có, mình muốn hiểu bản thân hơn <ArrowRight size={16} /></button><button className="secondary-button" onClick={onLater}>Để lúc khác</button></div></section> } 
function CoachingMessage({ onReady, onNotReady, onBack }: { onReady: () => void; onNotReady: () => void; onBack: () => void }) { return <section className="center-panel flow-panel"><button className="back-link" onClick={onBack}><ArrowLeft size={15} /> Quay lại</button><span className="tiny-symbol">🌱</span><p className="kicker">MỘT CHÚT DÀNH CHO CHÍNH BẠN</p><h1>Nếu bạn muốn đi sâu hơn vào câu chuyện của chính mình</h1><p>Có thể bạn đã biết mình muốn thay đổi. Nhưng đôi khi, điều khó nhất không phải là thay đổi… mà là hiểu vì sao mình lại trở thành phiên bản hiện tại.</p><p>Nếu bạn muốn tìm hiểu sâu hơn về chính mình, tặng bạn một buổi coaching 1:1 miễn phí nhé!</p><p>Bạn sẵn sàng nhận thông điệp này từ “vũ trụ” chứ?</p><div className="choice-actions"><button className="primary-button" onClick={onReady}>🌱 Tôi sẵn sàng <ArrowRight size={16} /></button><button className="secondary-button" onClick={onNotReady}>Mình chưa sẵn sàng</button></div></section> }
function CoachingForm({ form, setForm, onSubmit, onBack }: { form: { name: string; birthYear: string; gender: string; phone: string; contactTime: string; wish: string }; setForm: (value: { name: string; birthYear: string; gender: string; phone: string; contactTime: string; wish: string }) => void; onSubmit: () => void; onBack: () => void }) { return <section className="form-panel"><button className="back-link" onClick={onBack}><ArrowLeft size={15} /> Quay lại</button><p className="kicker">ĐỂ MÌNH HIỂU BẠN HƠN</p><h1>Một thông điệp dành riêng cho bạn</h1><p>Có thể bạn đã biết mình muốn thay đổi. Nhưng đôi khi, điều khó nhất không phải là thay đổi… mà là hiểu vì sao mình lại trở thành phiên bản hiện tại.</p><form onSubmit={(event) => { event.preventDefault(); onSubmit() }}><label>Họ và tên*<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Tên của bạn" /></label><label>Năm sinh*<input required inputMode="numeric" value={form.birthYear} onChange={(e) => setForm({ ...form, birthYear: e.target.value })} placeholder="Ví dụ: 1995" /></label><label>Giới tính*<select required value={form.gender} onChange={(e) => setForm({ ...form, gender: e.target.value })}><option value="">Chọn giới tính</option><option value="Nam">Nam</option><option value="Nữ">Nữ</option><option value="LGBT">LGBT</option></select></label><label>Số điện thoại liên hệ*<input required value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} placeholder="Số điện thoại" /></label><label>Thời gian có thể liên hệ*<input required value={form.contactTime} onChange={(e) => setForm({ ...form, contactTime: e.target.value })} placeholder="Ví dụ: 9:00 - 12:00" /></label><label>Điều bạn mong muốn nhận được từ buổi coaching này là gì?*<textarea required value={form.wish} onChange={(e) => setForm({ ...form, wish: e.target.value })} placeholder="Mong muốn hiểu hơn về bản thân..." /></label><button className="primary-button" type="submit">Gửi <Check size={16} /></button></form></section> }
