'use client'

import { useState } from 'react'
import { ArrowLeft, ArrowRight, Check, Sparkles } from 'lucide-react'

const cards = [
  { title: 'Đứa trẻ bên trong', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/_Sometimes%20you%20will%20never%20know%20the%20value%20of%20a%20moment%20until%20it%20becomes%20a%20memory_%E2%9C%A8%EF%B8%8F%20~%20_pink%20_pinkaesthetic%20_lightpink%20_garden-pQHrFWpVs155w9E5Sa98tiEZP15v9X.jpeg', message: 'Có một phiên bản nhỏ bé của bạn vẫn đang chờ được lắng nghe. Những điều bạn từng nghĩ là “không đáng gì” có thể đã để lại dấu vết sâu hơn bạn tưởng. Hôm nay, thay vì trách mình vì quá nhạy cảm, hãy thử hỏi: “Ngày đó, mình thật sự cần điều gì?”', question: 'Nếu được ôm lấy phiên bản nhỏ tuổi của mình ngay lúc này, bạn muốn nói gì với em ấy?' },
  { title: 'Bạn có đang thật sự ổn?', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/e85b80dfd1c1ccf6c6bd5a111af86b8b-W6IOUtc4lwENpy8uEj9zs8cZArZjre.jpg', message: '“Mình ổn” đôi khi chỉ là câu nói bạn đã quá quen miệng. Bạn không cần phải mạnh mẽ mọi lúc. Có những cảm xúc không cần được sửa chữa, chỉ cần được nhìn thấy và gọi đúng tên.', question: 'Hôm nay, cảm xúc nào đang cần bạn thành thật gọi tên?' },
  { title: 'Nhìn lại chính mình', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/04a0900b103887cf370c2506e8207571-KjCk0Hnvrv98A3ZWRvnOh2b0vuvqAZ.jpg', message: 'Người khác có thể là tấm gương, nhưng không phải mọi điều họ nói về bạn đều là sự thật. Đừng vội định nghĩa bản thân bằng ánh mắt của người khác.', question: 'Nếu không cần sự công nhận của bất kỳ ai, bạn muốn trở thành người như thế nào?' },
  { title: 'Cảm xúc không phải kẻ thù', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/62f36df49d634a29c9e8e8d787afe457-rwouStalnuRnipRaSKTzM2AQSuRTKi.jpg', message: 'Bạn không xấu chỉ vì bạn tức giận. Bạn không yếu đuối chỉ vì bạn buồn. Cảm xúc không đến để chống lại bạn. Nó đến để nói cho bạn biết bên trong mình đang có chuyện gì.', question: 'Cảm xúc của bạn đang cố bảo vệ điều gì?' },
  { title: 'Buông một phiên bản cũ', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/39f0c0f7a4179c0d970f36244d072ba8-rcSbJJl4RoDZ2nW7AYHA8qcqJ27PQm.jpg', message: 'Có những phiên bản của bạn từng rất cần thiết để bạn tồn tại. Nhưng không phải phiên bản nào cũng cần đi cùng bạn mãi mãi. Bạn có quyền thay đổi cách yêu, cách phản ứng, cách bảo vệ mình.', question: 'Điều gì bạn đã sẵn sàng nhẹ nhàng đặt xuống?' },
  { title: 'Đừng phản ứng quá nhanh', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/4019c97ebb852e803c95300e4226e78a-CEkBX3Uwoo1YLReP2DSAFn5V7UDllr.jpg', message: 'Có những lúc bạn không thật sự tức giận với người trước mặt. Bạn chỉ đang phản ứng với một vết thương cũ vừa bị chạm vào. Hãy dừng lại vài giây và hỏi: “Điều gì trong mình vừa bị chạm tới?”', question: 'Bạn cần thêm bao nhiêu khoảng lặng trước khi trả lời?' },
  { title: 'Bạn không cần phải hoàn hảo', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/5ad50b40d483950517ecd93a08c562c9-Em0hTGmQbj9HMx121TLWzJJWSxqiCv.jpg', message: 'Bạn không cần trở thành một phiên bản hoàn hảo hơn để xứng đáng được yêu thương. Phát triển bản thân là hiểu mình hơn, chấp nhận mình hơn, rồi từng chút một thay đổi những điều không còn phù hợp.', question: 'Hôm nay bạn có thể dịu dàng với mình ở điểm nào?' },
  { title: 'Điều bạn đang né tránh', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/0830728cb7eccdb519a99d4f53c9f590-Vv0O86D40TwnTlK5AGDYugPDkVxkZw.jpg', message: 'Có một điều bạn biết mình cần đối diện, nhưng vẫn đang cố lảng tránh. Bạn không cần giải quyết tất cả ngay hôm nay. Nhưng hãy đủ can đảm để thừa nhận: “Ừ, mình đang né tránh điều này.”', question: 'Một điều nhỏ bạn có thể thành thật với chính mình hôm nay là gì?' },
  { title: 'Học cách hiểu mình', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/436da258c38945e42b0b77553c29547c-cRR9ZoqYOkLODHPOlxILyHdPGQ3jEp.jpg', message: 'Bạn dành rất nhiều thời gian để đoán xem người khác nghĩ gì về mình. Nhưng đã bao lâu rồi bạn chưa thật sự hỏi chính mình: “Mình đang muốn gì? Mình đang cảm thấy gì?”', question: 'Điều gì khiến bạn hạnh phúc theo cách rất riêng?' },
  { title: 'Bạn đang thay đổi rồi', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/83e4b49dc6880ef2de718c6d1f91ce8b-dzwyz4yLg8KOrZMC8FnsSkXqwmuv5w.jpg', message: 'Có thể bạn chưa nhận ra, nhưng cách bạn nhìn mọi chuyện hôm nay đã khác ngày trước. Biết dừng lại, biết nói “không”, biết bảo vệ cảm xúc — đó đều là những dấu hiệu của trưởng thành.', question: 'Bạn đã đi được bao xa mà chưa kịp ghi nhận?' },
]

type Step = 'pick' | 'message' | 'quiz' | 'invite' | 'coaching' | 'form' | 'done'

export default function Page() {
  const [step, setStep] = useState<Step>('pick')
  const [selected, setSelected] = useState<number | null>(null)
  const [form, setForm] = useState({ name: '', birthYear: '', phone: '', contactTime: '', wish: '' })
  const [reflection, setReflection] = useState('')
  const [answers, setAnswers] = useState<Record<number, string>>({})
  const card = selected === null ? null : cards[selected]

  if (step === 'done') return <main className="tarot-page"><Header /><section className="center-panel"><span className="tiny-symbol"><Sparkles /></span><p className="kicker">CẢM ƠN BẠN</p><h1>Cảm ơn bạn đã sẵn sàng dành thời gian cho chính mình. 🌱</h1><p>Có thể bạn đến đây chỉ vì tò mò muốn biết “vũ trụ muốn nói gì với mình”. Nhưng biết đâu, điều bạn thật sự tìm thấy lại là một phiên bản của chính mình mà lâu nay bạn chưa có cơ hội lắng nghe.</p><strong>Chúng tôi sẽ liên hệ với bạn trong 1~2 ngày nữa nếu bạn được chọn. Hẹn gặp bạn trong buổi coaching nhé. 🤍</strong></section></main>

  return <main className="tarot-page"><Header /><div className="tarot-wrap">
    {step === 'pick' && <><section className="hero-copy"><p className="kicker">A LITTLE MESSAGE FROM THE UNIVERSE</p><h1>Hôm nay vũ trụ muốn<br /><em>nhắn nhủ bạn điều gì?</em></h1><p>Hít một hơi thật sâu. Nghĩ về điều đang khiến bạn bận lòng nhất lúc này.</p><p>Chọn một lá bài. Có thể thông điệp này chính là điều bạn cần nghe hôm nay.</p></section><CardGrid onPick={(index) => { setSelected(index); setStep('message') }} /></>}
    {step === 'message' && card && <Message card={card} reflection={reflection} setReflection={setReflection} onNext={() => setStep('quiz')} onBack={() => setStep('pick')} />}
    {step === 'quiz' && card && <SelfQuiz card={card} answers={answers} setAnswers={setAnswers} onNext={() => setStep('invite')} onBack={() => setStep('message')} />}
    {step === 'invite' && <Invite onNext={() => setStep('coaching')} onLater={() => setStep('done')} onBack={() => setStep('message')} />} 
    {step === 'coaching' && <CoachingMessage onReady={() => setStep('form')} onNotReady={() => setStep('done')} onBack={() => setStep('invite')} />}
    {step === 'form' && <CoachingForm form={form} setForm={setForm} onSubmit={() => setStep('done')} onBack={() => setStep('invite')} />}
  </div><footer>một khoảng lặng nhỏ để lắng nghe chính mình · 2026</footer></main>
}

function Header() { return <header className="tarot-header"><div className="brand"><span className="brand-icon"><Sparkles size={16} /></span> INNER / COMPASS</div><span className="header-note">SELF-AWARENESS JOURNAL</span></header> }
function CardGrid({ onPick }: { onPick: (index: number) => void }) { return <section className="card-grid" aria-label="Chọn một lá bài">{cards.map((card, index) => <button className="tarot-card" aria-label={`Chọn lá bài số ${index + 1}`} key={card.title} onClick={() => onPick(index)}><img src={card.image} alt="" /></button>)}</section> }
function Message({ card, reflection, setReflection, onNext, onBack }: { card: typeof cards[number]; reflection: string; setReflection: (value: string) => void; onNext: () => void; onBack: () => void }) { return <section className="message-layout"><button className="back-link" onClick={onBack}><ArrowLeft size={15} /> Chọn lại lá bài</button><div className="message-image"><img src={card.image} alt={card.title} /></div><div className="message-copy"><p className="kicker">THÔNG ĐIỆP DÀNH CHO BẠN HÔM NAY</p><h1>{card.title}</h1><p className="message-text">{card.message}</p><div className="reflection-box"><span>✦ Một câu hỏi dành cho bạn</span><p>“{card.question}”</p><textarea aria-label="Câu trả lời của bạn" value={reflection} onChange={(event) => setReflection(event.target.value)} placeholder="Viết điều đầu tiên xuất hiện trong tâm trí bạn..." /></div><button className="primary-button" onClick={onNext}>Cùng đi tìm hiểu chính mình nhé <ArrowRight size={16} /></button></div></section> }
function SelfQuiz({ card, answers, setAnswers, onNext, onBack }: { card: typeof cards[number]; answers: Record<number, string>; setAnswers: (value: Record<number, string>) => void; onNext: () => void; onBack: () => void }) { const questions = [`Khi nghĩ về “${card.title.toLowerCase()}”, điều gì xuất hiện đầu tiên trong bạn?`, 'Khi cảm xúc này xuất hiện, bạn thường phản ứng như thế nào?', 'Điều gì trong câu chuyện này khiến bạn muốn hiểu mình hơn?', 'Bạn muốn nhẹ nhàng thay đổi điều gì từ hôm nay?']; const options = ['Mình thường né tránh cảm xúc đó', 'Mình vẫn đang cố gắng hiểu điều đó', 'Mình đã bắt đầu thành thật với chính mình', 'Mình muốn nhìn sâu hơn và thay đổi']; return <section className="quiz-panel"><button className="back-link" onClick={onBack}><ArrowLeft size={15} /> Quay lại</button><p className="kicker quiz-kicker">🌱 MỘT CHÚT DÀNH CHO CHÍNH BẠN</p><h1>Cùng lắng nghe chính mình</h1><p className="quiz-intro">Không có câu trả lời đúng hay sai. Hãy chọn điều gần với bạn nhất.</p><div className="quiz-list">{questions.map((question, index) => <div className="question-card" key={question}><p className="question-title">{index + 1}. {question}</p><div className="option-grid">{options.map((option) => <label className={`quiz-option ${answers[index] === option ? 'is-selected' : ''}`} key={option}><input type="radio" name={`question-${index}`} value={option} checked={answers[index] === option} onChange={() => setAnswers({ ...answers, [index]: option })} />{option}</label>)}</div></div>)}</div><button className="primary-button quiz-submit" disabled={Object.keys(answers).length < questions.length} onClick={onNext}>Tiếp tục <ArrowRight size={16} /></button></section> }

function Invite({ onNext, onLater, onBack }: { onNext: () => void; onLater: () => void; onBack: () => void }) { return <section className="center-panel flow-panel"><button className="back-link" onClick={onBack}><ArrowLeft size={15} /> Quay lại</button><span className="tiny-symbol">🌱</span><p className="kicker">MỘT CHÚT DÀNH CHO CHÍNH BẠN</p><h1>Bạn có muốn hiểu thêm về bản thân mình không?</h1><p>Có những điều bên trong chúng ta chỉ nhận ra khi thật sự dành thời gian lắng nghe chính mình.</p><div className="choice-actions"><button className="primary-button" onClick={onNext}>Có, mình muốn hiểu bản thân hơn <ArrowRight size={16} /></button><button className="secondary-button" onClick={onLater}>Để lúc khác</button></div></section> } 
function CoachingMessage({ onReady, onNotReady, onBack }: { onReady: () => void; onNotReady: () => void; onBack: () => void }) { return <section className="center-panel flow-panel"><button className="back-link" onClick={onBack}><ArrowLeft size={15} /> Quay lại</button><span className="tiny-symbol">🌱</span><p className="kicker">MỘT CHÚT DÀNH CHO CHÍNH BẠN</p><h1>Nếu bạn muốn đi sâu hơn vào câu chuyện của chính mình</h1><p>Có thể bạn đã biết mình muốn thay đổi. Nhưng đôi khi, điều khó nhất không phải là thay đổi… mà là hiểu vì sao mình lại trở thành phiên bản hiện tại.</p><p>Nếu bạn muốn tìm hiểu sâu hơn về chính mình, tặng bạn một buổi coaching 1:1 miễn phí nhé!</p><p>Bạn sẵn sàng nhận thông điệp này từ “vũ trụ” chứ?</p><div className="choice-actions"><button className="primary-button" onClick={onReady}>🌱 Tôi sẵn sàng <ArrowRight size={16} /></button><button className="secondary-button" onClick={onNotReady}>Mình chưa sẵn sàng</button></div></section> }
function CoachingForm({ form, setForm, onSubmit, onBack }: { form: { name: string; birthYear: string; phone: string; contactTime: string; wish: string }; setForm: (value: { name: string; birthYear: string; phone: string; contactTime: string; wish: string }) => void; onSubmit: () => void; onBack: () => void }) { return <section className="form-panel"><button className="back-link" onClick={onBack}><ArrowLeft size={15} /> Quay lại</button><p className="kicker">ĐỂ MÌNH HIỂU BẠN HƠN</p><h1>Một thông điệp dành riêng cho bạn</h1><p>Có thể bạn đã biết mình muốn thay đổi. Nhưng đôi khi, điều khó nhất không phải là thay đổi… mà là hiểu vì sao mình lại trở thành phiên bản hiện tại.</p><form onSubmit={(event) => { event.preventDefault(); onSubmit() }}><label>Họ và tên*<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Tên của bạn" /></label><label>Năm sinh*<input required inputMode="numeric" value={form.birthYear} onChange={(e) => setForm({ ...form, birthYear: e.target.value })} placeholder="Ví dụ: 1995" /></label><label>Số điện thoại liên hệ*<input required value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} placeholder="Số điện thoại" /></label><label>Thời gian có thể liên hệ*<input required value={form.contactTime} onChange={(e) => setForm({ ...form, contactTime: e.target.value })} placeholder="Ví dụ: 9:00 - 12:00" /></label><label>Điều bạn mong muốn nhận được từ buổi coaching này là gì?*<textarea required value={form.wish} onChange={(e) => setForm({ ...form, wish: e.target.value })} placeholder="Mong muốn hiểu hơn về bản thân..." /></label><button className="primary-button" type="submit">Gửi <Check size={16} /></button></form></section> }
